/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.good.story

import kotlinx.coroutines.DelicateCoroutinesApi
import picocli.CommandLine
import java.util.concurrent.atomic.AtomicInteger
import kotlin.system.exitProcess

val virtualCounter = AtomicInteger(0)

class App {
    val greeting: String
        get() {
            return "Welcome to the Kotlin Coroutines Test!"
        }
}

@DelicateCoroutinesApi
fun main(args: Array<String>) {
    val exitCode = CommandLine(GoodStoryKotlinCommand()).execute(*args)
    exitProcess(exitCode)
}
