/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.good.story

import kotlinx.coroutines.DelicateCoroutinesApi
import picocli.CommandLine
import java.util.concurrent.atomic.AtomicInteger
import kotlin.system.exitProcess

val virtualCounter = AtomicInteger(0)

const val greeting: String = "Welcome to the Kotlin Coroutines on Loom Test!"

@DelicateCoroutinesApi
fun main(args: Array<String>) {
    val exitCode = CommandLine(GoodStoryKotlinLoomCommand()).execute(*args)
    exitProcess(exitCode)
}
