/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.good.story;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
