include ../Makefile
.SILENT: build-run

run:
	bash run.sh
set-jdk:
	cd .. && source loom-jdk.sh
build-run:
	echo "╔═════════════════════════════════════════════════╗"
	echo "║ Welcome to the Java Good Story Performance Test ║"
	echo "╚═════════════════════════════════════════════════╝"
	bash build.sh
