/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.kotlin.good.story

import kotlinx.coroutines.*
import org.jesperancinha.kotlin.good.story.GoodStoryCommand.Companion.DEFAULT_MASSIVE_REPEATS
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import picocli.CommandLine
import java.util.concurrent.atomic.AtomicInteger
import kotlin.system.exitProcess

val aiVirtualThread = AtomicInteger(0)

class App {
    val greeting: String
        get() {
            return "Welcome to the Kotlin Coroutines Test!"
        }
}

@DelicateCoroutinesApi
suspend fun main(args: Array<String>) {
//    GoodStoryCommand.generalTest(DEFAULT_MASSIVE_REPEATS.toInt())
    val exitCode = CommandLine(GoodStoryCommand()).execute(*args)
    exitProcess(exitCode)
}
