/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.good.story;

import java.util.concurrent.atomic.AtomicInteger;

public class GoodStoryJava {
    public static void main(String[] args) throws InterruptedException {
        final var ai = new AtomicInteger(10);
        final var virtualThread = Thread.startVirtualThread(
                () -> {
                    System.out.println("Imma be a Virtual Thread");
                    ai.getAndDecrement();
                }
        );
        virtualThread.join();
        System.out.println("Imma be the main Thread");
        System.out.println(ai.get());
    }
}