/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jesperancinha.good.story;

public class GoodStoryJava {
    public static void main(String[] args) {
        Thread.startVirtualThread(
                () -> System.out.println("Hello World")
        );
    }
}