name: GS - Report Run

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Java version check
        run: java -version

      - name: Build and make new Report
        run: make build-run

      - name: Build and Test
        run: mvn clean install jacoco:prepare-agent package jacoco:report

      - name: Coverage Reports
        run: mvn omni-coveragereporter:report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: Print Report
        run: cat Log.md
