name: GS - Report Run
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Local installation of Loom JDK
        run: make sdk-linux && ls -d loom*

      - name: Build and make new Report
        run: make build-run

      - name: Print Report
        run: cat Log.md
