name: GS - Report Run
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JEsperancinhaOrg Loom Action
        uses: JEsperancinhaOrg/loom-action@0.0.0-alfa-j

      - name: Build and make new Report
        run: make build-run

      - name: Print Report
        run: cat Log.md
