name: GS - Build with JDK 17
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'

      - name: Gradle Wrapper
        run: gradle install wrapper --gradle-version 7.4.2

      - name: Gradle version check
        run: gradle -version

      - name: Java version check
        run: java -version

      - name: Gradle Build
        run: cd java-good-story && gradle build test
