name: GS - Java - Loom Native Image Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'

      - uses: actions/checkout@v2

      - name: JEsperancinhaOrg Loom Action
        uses: JEsperancinhaOrg/loom-action@0.0.0-alfa-j

      - name: Java version check
        run: ls /home/runner/work/good-story/good-story/loom-jdk/jdk-19/bin && java -version

      - name: Gradle version check
        run: gradle -version

      - name: Gradle Wrapper
        run: gradle install wrapper --gradle-version 7.4.2

      - name: Gradle Build
        run: cd java-good-story && gradle build test
