name: GS - Kotlin
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: JEsperancinhaOrg Loom Action
        uses: JEsperancinhaOrg/loom-action@0.0.0-alfa-j

      - name: Java version check
        run: java -version

      - name: Maven Build
        run: cd kotlin-good-story; mvn clean install;
