name: GS - Java - Loom Native Image Build
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JEsperancinhaOrg Loom Action
        uses: JEsperancinhaOrg/loom-action@0.0.0-alfa-j

      - name: Java version check
        run: java -version

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Maven Build
        run: cd java-good-story && mvn clean install
